"""create users table with base.metadata

Revision ID: fddae75a3aef
Revises: a1b4c2a1c78c
Create Date: 2025-11-11 14:45:11.779058

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = 'fddae75a3aef'
down_revision: Union[str, Sequence[str], None] = 'a1b4c2a1c78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
